// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPUMVtG_Dgu-tjYSwYH1OdCq5mHVEvL9g',
    appId: '1:400103864484:web:b9fab86768066ab0970e31',
    messagingSenderId: '400103864484',
    projectId: 'steptzi-todo',
    authDomain: 'steptzi-todo.firebaseapp.com',
    storageBucket: 'steptzi-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt78uCtOk5TVfg4H1WNYN-6FnBMydj4lM',
    appId: '1:400103864484:android:1f02a24f4469575b970e31',
    messagingSenderId: '400103864484',
    projectId: 'steptzi-todo',
    storageBucket: 'steptzi-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmIe9DmuVsbCSB0CJNa9bT8o1P4a4XRc',
    appId: '1:400103864484:ios:edbed235b6c5f0c9970e31',
    messagingSenderId: '400103864484',
    projectId: 'steptzi-todo',
    storageBucket: 'steptzi-todo.appspot.com',
    iosClientId: '400103864484-eg2d1oolmjki50aqq4be2b8d5rpl5lcu.apps.googleusercontent.com',
    iosBundleId: 'ng.com.steptzi',
  );
}
